/*
 * ======================================
 * SPDX-License-Identifier: GPL-3.0-only
 * Copyright (c) 2026 Elizeu S. Souza
 * ======================================
 */

#include "meg.h"

LOCAL static bool analsisok = false;

/* Scope limit. */
constexpr static size SLIMIT = 1024;
/* Socope stack. */
LOCAL static scope *sstck[SLIMIT];
/* Scope count. */
LOCAL static u32 scount;
/* Default types. */
LOCAL static type
	*ti08 = &(type){.k = TINT, .sz = 1, .sign = true},
	*ti16 = &(type){.k = TINT, .sz = 2, .sign = true},
	*ti32 = &(type){.k = TINT, .sz = 4, .sign = true},
	*ti64 = &(type){.k = TINT, .sz = 8, .sign = true},
	*tu08 = &(type){.k = TINT, .sz = 1, .sign = false},
	*tu16 = &(type){.k = TINT, .sz = 2, .sign = false},
	*tu32 = &(type){.k = TINT, .sz = 4, .sign = false},
	*tu64 = &(type){.k = TINT, .sz = 8, .sign = false},
	*tf32 = &(type){.k = TFLOAT, .sz = 4},
	*tf64 = &(type){.k = TFLOAT, .sz = 8},
	*trune = &(type){.k = TRUNE, .sz = 4},
	*tbool = &(type){.k = TBOOL, .sz = 1},
	*astr = &(type){.k = TARRAY, .asz = -1};	// .sz should be set in analyserinit().

static decl *dtype(
	str id,
	type *ty
) {
	struct decl *d;

	d = newdecl((loc){}, DTYPE, id);
	d->ty = ty;
	return d;
}

void analyserinit() {
	scope *mags;

	/* Set 'str' alias a an array of bytes. */
	astr->ty = tu08;

	/* Initializes the magic scope. */
	mags = newscope();

	/* Declares all. */
	declare(mags, dtype("i08", ti08));
	declare(mags, dtype("i16", ti16));
	declare(mags, dtype("i32", ti32));
	declare(mags, dtype("i64", ti64));
	declare(mags, dtype("u08", tu08));
	declare(mags, dtype("u16", tu16));
	declare(mags, dtype("u32", tu32));
	declare(mags, dtype("u64", tu64));
	declare(mags, dtype("f32", tf32));
	declare(mags, dtype("f64", tf64));
	declare(mags, dtype("rune", trune));
	declare(mags, dtype("bool", tbool));
	/* Aliases. */
	declare(mags, dtype("str", astr));

	/* Stack it. */
	sstck[0] = mags;
	scount = 1;

	analsisok = true;
}

static decl *findecl(loc l, str id);
static void aply(loc l, type **x, struct type *y);
static void ascope(scope *s);
static type *ahint(hint *h);
static void adecl(decl *d);
static void aexpr(expr *e);
[[maybe_unused]]
static void astmt(stmt *s);

static void aply(loc l, type **px, type *y) {
	type *x = *px;

	if (x->k == TNONE) {
		*px = y;
		return;
	}

	if (!tyeql(x, y))
		lerro(l, "Aplying to a different type.");
}

static decl *findecl(loc l, str id) {
	decl *x;
	int i = scount;

	while (i--) {
		x = getdecl(sstck[i], id);
		if (x)
			return x;
	}

	lerro(l, "Use of undeclared identifier '%s'.", id);
	return nullptr;
}

static type *ahint(hint *h) {
	type *t;

	switch (h->k) {
	case HNONE:
		t = newtype(h->l, TNONE);
		break;
	case HEXPR:
		aexpr(h->e);
		if (h->e->k != EDREF) {
			lerro(
				h->e->l,
				"Expected a declaration"
				" reference."
			);
			t = newtype(h->l, TNONE);
			break;
		}

		if (h->e->d->k != DTYPE) {
			lerro(h->l, "Not a type.");
			t = newtype(h->l, TNONE);
			break;
		}
		t = h->e->d->ty;
		break;
	case HREF:
		t = newtype(h->l, TREF);
		t->ty = ahint(h->ty);
		break;
	case HFUNC:
		adeus("Functional types are unsupported.");
	case HSTRUC:
		t = newtype(h->l, TSTRUC);
		ascope(h->s);
		t->s = h->s;
		break;
	case HARRAY:
		t = newtype(h->l, TARRAY);
		t->ty = ahint(h->ty);

		/* Slice? */
		if (!h->e) {
			t->sz = -1;
			break;
		}

		/* Gets the array size. */
		aexpr(h->e);
		if (h->e->k != EINTEGER) {
			lerro(
				h->e->l,
				"Expected integer constant."
			);
			t->sz = 0;
			break;
		}
		t->sz = h->e->lint;
		break;
	}

	return t;
}

static void adecl(decl *d) {
	switch (d->k) {
	case DNONE:
		/*
		 * May be intentionally
		 * generated by parser.c,
		 * so break.
		 */
		break;
	case DFUNC:
		ascope(d->s);
		d->ty = newtype(d->l, TFUNC);
		d->ty->s = d->s;
		d->ty->ty = ahint(d->h);
		if (d->e) {
			sstck[scount++] = d->s;
			aexpr(d->e);
			aply(d->e->l, &d->ty->ty, d->e->ty);
			scount--;
			break;
		}

		if (!d->ty->ty->k)
			lerro(d->ty->ty->l, "Can't infer result type.");
		break;
	case DOBJ:
		d->ty = ahint(d->h);
		if (d->e) {
			aexpr(d->e);
			aply(d->e->l, &d->ty, d->e->ty);
			break;
		}

		if (!d->ty->k)
			lerro(d->ty->l, "Can't infer type.");
		break;
	case DTYPE:
		/* May be aliases. */
		if (d->h)
			d->ty = ahint(d->h);
		break;
	}
}

static void aexpr(expr *e) {
	type *ety;
	expr *arg;
	dbuk *par;

	switch (e->k) {
	case ENONE:
		/*
		 * May be intentionally
		 * generated by parser.c,
		 * so break.
		 */
		break;
	case EADD:
	case ESUB:
	case EMUL:
	case EDIV:
	case EREM:
	case EAND:
	case EBOR:
	case EEOR:
		aexpr(e->lhs);
		aexpr(e->rhs);
		goto aplybin;
	case ELAND:
	case ELOR:
	case EEQL:
	case ENEQ:
	case EGTR:
	case ELSS:
	case EGEQ:
		aexpr(e->lhs);
		aexpr(e->rhs);
aplybin:
		aply(e->l, &e->ty, e->lhs->ty);
		aply(e->l, &e->ty, e->rhs->ty);
		break;
	case EREF:
	case ENEG:
	case ENOT:
	case EPLUS:
	case EMINUS:
		aexpr(e->lhs);
		aply(e->l, &e->ty, e->lhs->ty);
		break;
	case ECALL:
		/* TODO: Type cast. */
		/* Analyses the expr being called. */
		aexpr(e->lhs);
		ety = e->lhs->ty;

		/* Check its type and result type. */
		if (ety->k != TFUNC) {
			lerro(e->lhs->l, "Only functionals can be called.");
			break;
		} else {
			aply(e->l, &e->ty, ety->ty);
		}

		/* Check argument count. */
		if (e->n != ety->s->dc) {
			lerro(
				e->l,
				"Expected %zu parameters,"
				" received %zu.",
				ety->s->dc,
				e->n
			);
			break;
		}

		/* Analyses the arguments. */
		arg = e->rhs;
		par = ety->s->fst;
		while (arg) {
			aexpr(arg);
			aply(
				arg->l,
				&arg->ty,
				par->d->ty
			);

			arg = arg->next;
			par = par->next;
		}
		break;
	case EPAREN:
		aexpr(e->lhs);
		aply(e->l, &e->ty, e->lhs->ty);
		break;
	case EDREF:
		e->d = findecl(e->l, e->str);
		if (e->d)
			aply(e->l, &e->ty, e->d->ty);
		else
			e->d = newdecl(e->l, DNONE, "!invalid");
		break;
	case EINTEGER:
		e->ty = ti32;
		break;
	case EFLOAT:
		e->ty = tf32;
		break;
	case EBOOL:
		e->ty = tbool;
		break;
	case ERUNE:
		e->ty = trune;
		break;
	case ESTRING:
		e->ty = astr;
		break;
	default:
		adeus("Unsupported expression.");
	}
}

static void ascope(scope *s) {
	sstck[scount++] = s;

	auto b = s->fst;
	while (b) {
		adecl(b->d);
		b = b->next;
	}

	scount--;
}

void analyse(unit *u) {
	if (!analsisok)
		adeus("May not analyse now.");

	ascope(u->s);
	analsisok = false;
}
