/*
 * ======================================
 * SPDX-License-Identifier: GPL-3.0-only 
 * Copyright (c) 2026 Elizeu S. Souza    
 * Generated by /tools/make-rune-tables. 
 * ======================================
 */
/* Must be at /megc. */

#pragma once

#include "meg.h" // IWYU pragma: export

bool isridstart(rune r);

bool isridcontinue(rune r);

bool isrdigit(rune r);

bool isrspace(rune r);

i32 getdigitval(rune r);
