/*
 * ======================================
 * SPDX-License-Identifier: GPL-3.0-only
 * Copyright (c) 2026 Elizeu S. Souza
 * ======================================
 */

/*
 * I'm not good at Go,
 * but this file will
 * generate the runetables,
 * that megc uses to identify
 * UTF-8 identifiers.
 */

package main

import (
	"fmt"
	"io"
	"net/http"
	"os"
)

func prerr(msg string, va ...any) {
	fmt.Print("ERROR: ")
	fmt.Printf(msg, va...)
	fmt.Println("")
}

func get(url string) ([]byte, error) {
	resp, err := http.Get(url)
	if err != nil {
		prerr("Failed to get '%s', err: %s", url, err)
		return nil, err
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		prerr("Response from '%s' status isn't ok, err '%s'", url, err)
		return nil, err
	}

	ret, err := io.ReadAll(resp.Body)
	if err != nil {
		prerr("Failed to read '%s', err: %s", url, err)
		return nil, err
	}

	ret = append(ret, 0)
	return ret, nil
}

type codepair [2]string
type derivedCoreProp struct {
	idStart []codepair
	idContinue []codepair
}

type codeAndData struct {
	code string
	data string
}
type unicodeData struct {
	nd []codeAndData
	zs []string
}

func  parseDerivedCoreProp(s *derivedCoreProp,buf []byte) {
	i := 0

	for {
		b := buf[i]
		if b == 0 {
			break
		}

		/* Skips any invalid line. */
		if b == '\n' {
			i++
			continue
		}
		if b == '#' {
			for buf[i] != '\n' {
				i++
			}
			i++
			continue
		}

		/* Parse the code. */
		var pair codepair

		p := i
		for buf[p] != ' ' && buf[p] != '.' {
			p++
		}

		pair[0] = string(buf[i:p])
		i = p

		if string(buf[i:i+2]) == ".." {
			i += 2
			p = i
			for buf[p] != ' ' {
				p++
			}

			pair[1] = string(buf[i:p])
			i = p
		} else {
			pair[1] = pair[0]
		}

		/* Skips spaces and ';'. */
		for buf[i] == ' ' {
			i++
		}

		if buf[i] != ';' {
			prerr("Expected ';', found %c", rune(buf[i]))
			return
		}
		i++

		for buf[i] == ' ' {
			i++
		}

		/* Parses the category. */
		p = i
		for buf[p] != ' ' {
			p++
		}

		categ := buf[i:p]
		switch string(categ) {
		case "ID_Start":
			s.idStart = append(s.idStart, pair)
		case "ID_Continue":
			s.idContinue = append(s.idContinue, pair)
		}

		/* Goes to the next line. */
		i = p
		for buf[i] != '\n' {
			i++
		}
		i++
	}
}

func parseUnicodeData(s *unicodeData, buf []byte) {
	i := 0

	for {
		if buf[i] == 0 {
			break
		}

		p := i
		for buf[p] != ';' {
			p++
		}
		code := string(buf[i:p])
		i = p

		i++// Skips ';'

		/* Skips the character name. */
		for buf[i] != ';' {
			i++;
		}

		i++ // Skips ';'.

		/* Gets the general category. */
		p = i
		for buf[p] != ';' {
			p++
		}
		categ := string(buf[i:p])
		i = p

		i++ // Skips ';',

		switch categ {
		case "Nd":
			/* Skips 3 ';', the 7th field. */
			c := 0
			for c < 3 {
				if buf[i] == ';' {
					c++
				}
				i++
			}

			/* Get the decimal value. */
			p = i
			for buf[p] != ';' {
				p++
			}
			data := string(buf[i:p])
			i = p

			s.nd = append(s.nd, codeAndData{code, data})
			goto endline
		case "Zs":
			/* Nothing to do, just stores the code. */
			s.zs = append(s.zs, code)
		}

		endline:
			for buf[i] != '\n' {
				i++
			}
			i++
	}
}

func genUnicodeData(out *os.File){
	const url = "https://www.unicode.org/Public/UCD/latest/ucd/UnicodeData.txt"

	buf, err := get(url)
	if err != nil {
		os.Exit(1)
	}

	var data unicodeData
	parseUnicodeData(&data, buf)

	out.WriteString("static i32 digit[][2] = {\n")
	for _, cd := range(data.nd) {
		f := fmt.Sprintf("\t{0x%s, %s},\n", cd.code, cd.data)
		out.WriteString(f)
	}
	out.WriteString("};\n")

	out.WriteString("static rune space[] = {\n")
	for _, zs := range(data.zs) {
		f := fmt.Sprintf("\t0x%s,\n", zs)
		out.WriteString(f)
	}
	out.WriteString("};\n")
 }

func genDerivedCoreProp(out *os.File) {
	const url = "https://www.unicode.org/Public/UCD/latest/ucd/DerivedCoreProperties.txt";

	buf, err := get(url)
	if err != nil {
		os.Exit(1)
	}

	var prop derivedCoreProp
	parseDerivedCoreProp(&prop, buf)

	out.WriteString(
		"/*\n"+
		" * ======================================\n"+
		" * SPDX-License-Identifier: GPL-3.0-only \n"+
		" * Copyright (c) 2026 Elizeu S. Souza    \n"+
		" * Generated by /tools/make-rune-tables. \n"+
		" * ======================================\n"+
		" */\n",
	)
	out.WriteString(
		"/* Must be at /megc. */\n"+
		"\n#include \"runetable.h\"\n"+
		"#include <stdlib.h>\n",
	)

	indent := true

	/* Writes id_start table. */
	out.WriteString("\nstatic rune id_start[][2] = {")
	for _, pair := range(prop.idStart) {
		if indent {
			out.WriteString("\n\t")
		} else {
			out.WriteString(" ")
		}
		indent = !indent

		f := fmt.Sprintf("{0x%s, 0x%s},", pair[0], pair[1])
		out.WriteString(f)
	}
	out.WriteString("\n};\n")

	indent = true

	/* Writes id_continue table. */
	out.WriteString("\nstatic rune id_continue[][2] = {")
	for _, pair := range(prop.idContinue) {
		if indent {
			out.WriteString("\n   ")
		} else {
			out.WriteString(" ")
		}
		indent = !indent

		f := fmt.Sprintf("{0x%s, 0x%s},", pair[0], pair[1])
		out.WriteString(f)
	}
	out.WriteString("\n};\n")
}

func genFuncs(out *os.File) {
	out.WriteString("\n/* Functions. */\n")

	out.WriteString(`
static int rangecmp(const void *x, const void *y) {
	rune key = *(rune *) x;
	rune *pair = (rune *) y;
	if (key >= pair[0] && key <= pair[1]) {
		return 0;
	}

	if (key < pair[0]) {
		return -1;
	}

	return 1;
}
`)

	out.WriteString(`
bool isridstart(rune r) {
	size nmemb = sizeof id_start / sizeof id_start[0];
	if (bsearch(
					&r, id_start,
					nmemb, sizeof id_start[0],
					rangecmp) == nullptr) {
		return false;
	}
	return true;
}
`)

	out.WriteString(`
bool isridcontinue(rune r) {
	size nmemb = sizeof id_continue / sizeof id_continue[0];
	if (bsearch(&r, id_continue,
					nmemb, sizeof id_continue[0],
					rangecmp) == nullptr) {
		return false;
	}
	return true;
}
`)

	out.WriteString(`
static int unicmp(const void *x, const void *y) {
	rune key = *(rune *) x;
	rune val = *(rune *) y;
	if (key == val) {
		return 0;
	}

	if (key < val) {
		return -1;
	}

	return 1;
}
`)

	out.WriteString(`
bool isrspace(rune r) {
	size nmemb = sizeof space / sizeof space[0];
	if (bsearch(&r, space, nmemb, sizeof space[0], unicmp) == nullptr) {
		return false;
	}
	return true;
}
`)

	out.WriteString(`
bool isrdigit(rune r) {
	size nmemb = sizeof digit / sizeof digit[0];
	if (bsearch(&r, digit, nmemb, sizeof digit[0], unicmp) == nullptr) {
		return false;
	}
	return true;
}
`)

	out.WriteString(`
i32 getdigitval(rune r) {
	size nmemb = sizeof digit / sizeof digit[0];
	auto result = (i32*) bsearch(&r, digit, nmemb, sizeof digit[0], unicmp);
	if (result == nullptr) {
		return -1;
	}
	return result[1];
}
`)
}

func genHeader(out *os.File ) {
	out.WriteString(
		"/*\n"+
		" * ======================================\n"+
		" * SPDX-License-Identifier: GPL-3.0-only \n"+
		" * Copyright (c) 2026 Elizeu S. Souza    \n"+
		" * Generated by /tools/make-rune-tables. \n"+
		" * ======================================\n"+
		" */\n",
	)
	out.WriteString(
		"/* Must be at /megc. */\n" +
		"\n#pragma once\n"+
		"\n#include \"meg.h\" // IWYU pragma: export\n",
	)

	out.WriteString("\nbool isridstart(rune r);\n")
	out.WriteString("\nbool isridcontinue(rune r);\n")
	out.WriteString("\nbool isrdigit(rune r);\n")
	out.WriteString("\nbool isrspace(rune r);\n")
	out.WriteString("\ni32 getdigitval(rune r);\n")
}

func main() {
	outc, err := os.Create("runetable.c")
	if err != nil {
		prerr("While creating 'runetable.c', err: %s", err)
		os.Exit(1)
	}
	defer outc.Close()

	genDerivedCoreProp(outc)
	genUnicodeData(outc)
	genFuncs(outc)

	outh, err := os.Create("runetable.h")
	if err != nil {
		prerr("While creating 'runetable.h', err: %s", err)
		os.Exit(1)
	}
	defer outh.Close()

	genHeader(outh)
}
